argoproj/notifications-engine

.golangci.yml, pkg/services/email.go, pkg/services/slack_test.go, pkg/services/teams.go, pkg/services/webhook.go
=> chore: improve golangci-lint add goimports

docs/services/email.md, docs/services/github.md, docs/services/grafana.md, docs/services/mattermost.md, docs/services/opsgenie.md, docs/services/overview.md, docs/services/slack.md, docs/services/teams.md, docs/services/telegram.md, docs/services/tools.go, docs/services/webhook.md
PR moves services specific documentation from https://github.com/argoproj-labs/argocd-notifications
=> docs: add services documentation

README.md
=> docs: more content in README.md

pkg/triggers/service.go
=> refactor: engine should tolerate triggers without 'when' property

docs/services/slack.md
Fix typos and rephrase sentences
=> Fix typos in slack.md

docs/services/teams.md, pkg/services/teams.go, pkg/services/teams_test.go
This pull requests is the implementation of argoproj-labs/argocd-notifications#263
=> feat: add summary field into teams message

pkg/api/factory.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/state.go
=> refactor: support re-using existing object informer to create notification controller

pkg/controller/controller.go
=> feat: WithAdditionalDestinations with WithAlterDestinations to support removing destinations

docs/services/webhook.md
=> docs: improve webhook docs

.github/workflows/ci.yaml
=> chore: split lint jobs

docs/services/overview.md, docs/services/rocketchat.md
PR is based on https://github.com/argoproj/notifications-engine/pull/6 and resolved reviewer all reviewer's suggestions except adding screenshot.
=> docs: Add documentation for RocketChat

docs/services/tools.go, pkg/docs/docs.go
=> feat: embed services docs to simplify including them in consumers projects

pkg/triggers/service.go
=> fix: add expr error log

examples/certmanager/README.md
=> docs: Fix typo

docs/services/webhook.md
=> docs: add send slack message using webhook

docs/services/slack.md
=> docs: improve slack docs

docs/services/email.md
=> docs: add insecure_skip_verify for email docs

pkg/controller/controller.go, pkg/subscriptions/annotations.go, pkg/subscriptions/annotations_test.go
https://github.com/argoproj-labs/argocd-notifications/issues/317
=> fix: add annotations nil check

docs/services/alertmanager.md, docs/services/overview.md, pkg/services/alertmanager.go, pkg/services/alertmanager_test.go, pkg/services/services.go
Delivery for https://github.com/argoproj/notifications-engine/pull/38
=> Alertmanager

pkg/services/telegram.go
Send a message to Telegram as Markdown
=> feat: support send message to Telegram as markdown

docs/services/slack.md
Fixes [[#8776](https://github.com/argoproj/argo-cd/issues/8776)]
Signed-off-by: Ole-Martin Bratteng <1681525+omBratteng@users.noreply.github.com>
=> docs: fixes the YAML codefence for `Slack` notification service

pkg/util/slack/client_test.go
=> test: check if slack message is a post or an update

docs/services/googlechat.md
Signed-off-by: emirot <emirot.nolan@gmail.com>
Initially in https://github.com/argoproj/argo-cd/pull/11220
=> chore: fix typo in googlechat

examples/certmanager/controller/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go
This is intended to provide a generic framework for processing notification delivery/error events.
For example, a user could instantiate a controller with some business logic to monitor when notifications are misconfigured or fail to send to a particular service.
Issues: https://github.com/argoproj/notifications-engine/issues/135
=> add callbacks to process notification delivery/err

go.mod, go.sum, pkg/services/github.go, pkg/services/github_test.go
Fixes https://github.com/argoproj/notifications-engine/issues/82
=> feat: add support for passing gh appID, installationID via K8s secret

go.mod, go.sum
updating grafana service documentation w/ possible parameters for cm
=> updating grafana service documentation w/ possible parameters for cm

pkg/services/teams.go
=> fix error message

.github/workflows/ci.yaml, .golangci.yml, pkg/api/config.go, pkg/api/factory.go, pkg/cmd/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/services/alertmanager.go, pkg/services/awssqs.go, pkg/services/awssqs_test.go, pkg/services/email_test.go, pkg/services/grafana.go, pkg/services/mattermost.go, pkg/services/rocketchat.go, pkg/services/slack.go, pkg/services/webex.go, pkg/services/webex_test.go, pkg/triggers/service_test.go, pkg/util/slack/client.go
There's a major upgrade of it. This is an initial upgrade to make the changes as minimal as possible.
=> chore: bump golanglint-ci

.golangci.yml, examples/certmanager/cli/main.go, examples/certmanager/controller/main.go, pkg/api/config.go, pkg/api/config_test.go, pkg/api/factory.go, pkg/api/factory_test.go, pkg/cmd/context.go, pkg/cmd/trigger_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/docs/docs.go, pkg/services/alertmanager.go, pkg/services/awssqs.go, pkg/services/awssqs_test.go, pkg/services/github.go, pkg/services/opsgenie_test.go, pkg/services/pagerdutyv2.go, pkg/services/rocketchat.go, pkg/services/slack.go, pkg/services/slack_test.go, pkg/services/webhook.go, pkg/subscriptions/annotations.go
Try to slowly converge towards what exists on argo-cd.
=> chore: more lint
