pkg/cmd/tools.go
=> use 'command.PersistentPreRun' instead of 'cobra.OnInitialize' to avoid always running notifications related code during initialization

docs/services/email.md, pkg/services/email.go
=> feat: support email SendHtml

docs/services/slack.md
To fix the numbered list in Slack Configuration https://argocd-notifications.readthedocs.io/en/stable/services/slack/
Added indent to the code block
=> docs: Fix numbered list for slack configuration

docs/services/slack.md, pkg/services/slack.go, pkg/services/slack_test.go, pkg/templates/service.go
Support message aggregation feature by slack threads API.
Detail is following.
* https://github.com/argoproj-labs/argocd-notifications/issues/319
=> feat: add message aggregation feature by slack threads API

go.mod, go.sum, pkg/services/telegram.go
Hi, 
Here's a small PR to update the tgbotapi version. I don't think Telegram increasing user IDs to 52 significant bits would affect this, but the version bump also removes a dependency.
Argo is a fantastic collection of software and it's cool to see my library getting used here :)
=> chore: bump tgbotapi version

pkg/services/slack_test.go, pkg/util/slack/client_test.go
Closes https://github.com/argoproj/notifications-engine/issues/70
Reflection-based tests are pretty fragile and expensive to maintain. So I propose to drop them instead of spending time after every golang upgrade.
=> chore: drop reflection based slack client tests

.github/workflows/ci.yaml
Signed-off-by: Ravi Hari <ravireliable@gmail.com>
Had similar issue in argo-rollouts: https://github.com/argoproj/argo-rollouts/pull/1958
=> fix: build/lint is broken due to dependencies changes

pkg/services/github.go, pkg/services/github_test.go
This is for fixing https://github.com/argoproj/notifications-engine/issues/90
=> fix: refer to the revision of a specific sync operation instead of the current revision

docs/services/slack.md
Related to [#80], borked YAML was introduced in #65.
Codefences in lists must be created with indentation, otherwise they'll be rendered as inline code
Signed-off-by: Ole-Martin Bratteng <1681525+omBratteng@users.noreply.github.com>
=> docs: fixes the YAML codefence for `Slack` notification service

docs/services/slack.md
hello,
I've added the yaml markdown that was missing.
Signed-off-by: Pier <53210578+pie-r@users.noreply.github.com>
=> docs: use yaml syntax in markdown

go.mod, go.sum
This change removes the need for [this replace line](https://github.com/argoproj/notifications-engine/blob/f37afd3848b6cff3a755cb6b60abfab101d29c06/go.mod#L37) in the go.mod files of notifications-engine and its dependents.
The [diff between gomodules.xyz/notify v0.1.0 and v0.1.1](https://github.com/gomodules/notify/compare/v0.1.0...v0.1.1) is only a change to go.mod/go.sum which I think was intended to fix this issue.
=> Update gomodules.xyz/notify to v0.1.1

docs/services/googlechat.md, pkg/services/googlechat.go, pkg/services/googlechat_test.go
Support posting messages to a chat thread based on an arbitrary key.
Example threads:
See Chat API create message [query parameters](https://developers.google.com/chat/api/reference/rest/v1/spaces.messages/create#query-parameters).
=> feat: add Google Chat thread support

docs/services/webhook.md, pkg/services/webhook.go, pkg/services/webhook_test.go
The generic webhook is hardcoded to not skip insecure. I would like to be able to specify this as a webhook option.
=> Allow user to skip verification on self-signed certs

go.mod
Signed-off-by: emirot <emirot.nolan@gmail.com>
Update golang version to 1.17
Update to match what is used in tests https://github.com/argoproj/notifications-engine/blob/master/.github/workflows/ci.yaml#L14 
@pasha-codefresh
=> chore: update golang to match testing version used

docs/services/newrelic.md, pkg/services/newrelic.go, pkg/services/newrelic_test.go, pkg/services/services.go
Hi folks,
My company is in the process of rolling out New Relic internally and I saw an opportunity for adding a new notification service for it to integrate with its [Deployment Marker](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/) functionality.
Not sure if the contributing process involving opening up an issue first, etc, so just let me know if changes are need to be made.
Also, pretty new to the Argoproj codebase, so let me know if I missed any aspect of adding a new notification service, or if there are any other considerations/suggestions. Haven't tested e2e, not sure the best way of doing so within this codebase or integrated with the ArgoCD one.
Issue: #93
=> feat(services): add NewRelic service

docs/services/github.md, pkg/services/github.go, pkg/services/github_test.go
The Github service uses the hard-coded argo spec paths to extract the repo URL and synced revision. To make the notification engine generic, this commit makes the paths configurable. If they're not specified, it falls back to the argo API.
Fixes https://github.com/argoproj/notifications-engine/issues/59
Signed-off-by: Nan Yu nanyu@google.com
=> Make the Github's repoURL and revision paths configurable

examples/certmanager/README.md, examples/certmanager/controller/main.go, pkg/controller/controller_test.go, pkg/controller/state.go, pkg/subscriptions/annotations.go, pkg/subscriptions/annotations_test.go
This is intended to make the prefix configurable for projects using this controller which are not in the Argo ecosystem. This allows such projects to use an annotation key that is consistent with the conventions of their project.
Issues: https://github.com/argoproj/notifications-engine/issues/139
=> make the annotation key prefix configurable

go.mod, go.sum, pkg/api/config.go, pkg/cmd/context.go, pkg/cmd/trigger_test.go, pkg/services/googlechat.go, pkg/services/services.go, pkg/subscriptions/annotations.go, pkg/util/misc/misc.go
> Looks great! It would also be good to update the [notification-engine (https://github.com/argoproj/notifications-engine) as well.
_Originally posted by @blakepettersson in https://github.com/argoproj/argo-cd/issues/13292#issuecomment-1515918894_
This PR is part of https://github.com/argoproj/argo-cd/pull/13292 to completely replace `github.com/ghodss.yaml` with `sigs.k8s.io/yaml`.
=> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

docs/services/pagerduty_v2.md, pkg/services/pagerdutyv2.go, pkg/services/pagerdutyv2_test.go, pkg/services/services.go
This PR adds a new version of the PagerDuty service using the Events API v2 instead of the Incident Creation API. The previous API was not meant for use by automation, whereas the Events API matches existing patterns for how to trigger events/incidents in PagerDuty with an integration. I've added docs to note the new configuration.
To avoid a breaking change, this has a service name of `pagerdutyv2` instead of `pagerduty`.
Fixes #89.
Signed-off-by: Eric Tendian <erictendian[at]gmail.com>
=> feat: Adding a new version of the PagerDuty integration which uses Events API v2

docs/services/slack.md
The lack of indentation messed up Markdown's automatic enumeration. Before this change, the list went went "1, 2, 3, 4, 5, 6, 7, 8, 1, 1, 1". Now it goes "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11" as it should.
=>  Fix indentation in Slack documentation

docs/services/github.md, pkg/services/github.go, pkg/services/github_test.go
Hi there, thanks for adding support for Deployments to the Notifications Engine.  I was testing out the support and ran into issues trying to deploy an older ref from the default branch.  The notifications controller would report an error when merging the default branch into the commit referenced.  Upon reading the docs, it looks like this is the [intended behavior](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#create-a-deployment) so it seems reasonable to allow users to disable this feature when they would not like their deployment updated against the default branch. 
This PR was tested against an internal custom ArgoCD build and it resolved our issues with deployments only functioning on the latest commit in a default branch.  
I'm happy to make any …
=> GitHub Deployment - Allow Automerge configuration

docs/services/github.md, pkg/services/github.go, pkg/services/github_test.go
Closes #136
Similarly to #151, this PR adds the integration with Github to allow commenting on a PullRequest.
I tested it working as expected in a custom installation of ArgoCD using the code in this PR for the notification-engine
**Note**: the code in this PR currently **creates a new comment** every time, it does not update the existing one. To me, the possibility to edit the previous comment could be seen as a future improvement
=> Add GitHub Pull Request comments integration

.github/workflows/ci.yaml
V4 version of codecov cant be used right now
=> fix: revert codecov to v3

docs/services/slack.md
My first attempt of using the Slack service failed with `invalid_auth`, so I thought that this documentation would need to be updated so not everyone need to play the guessing game.
=> Update documentation for Slack options

docs/services/opsgenie.md, docs/services/pagerduty.md, docs/services/pagerduty_v2.md
This PR fixes the case of two vendor names - PagerDuty and Opsgenie - in the docs just to make sure they're formal and aligned to those vendor's branding.
These don't look to be autogenerated in this repo, but best I understand get defined here and "pulled down" into CD and Rollouts?
This should help support upstream doc fix in https://github.com/argoproj/argo-cd/pull/16233.  May require downstream PRs in both Argo CD and Argo Rollouts, lest the codegen steps in those fail (?).
=> docs: Fix case of vendor names

docs/services/awssqs.md, pkg/services/awssqs.go, pkg/services/awssqs_test.go
This should allow the awssqs service to send messages to FIFO SQS queues which require a MessageGroupId to be set.
=> feat(awssqs): Support sending messages to SQS FIFO queues

docs/services/alertmanager.md, docs/services/awssqs.md, docs/services/email.md, docs/services/github.md, docs/services/googlechat.md, docs/services/grafana.md, docs/services/mattermost.md, docs/services/newrelic.md, docs/services/opsgenie.md, docs/services/pagerduty.md, docs/services/pagerduty_v2.md, docs/services/pushover.md, docs/services/rocketchat.md, docs/services/slack.md, docs/services/teams.md, docs/services/telegram.md, docs/services/webex.md, docs/services/webhook.md
Related to https://github.com/argoproj/argo-cd/pull/17002
=> docs: use real cm name instead of placeholder

pkg/services/github.go
Try to list existing deployment with the same sha/environment/ref and reuse it if found. This allows ArgoCD notification to update the same deployment with multiple deployment status instead of creating a new one on each deployment notification.
=> github: reuse existing deployment when sending new notification

pkg/services/opsgenie.go, pkg/services/opsgenie_test.go
This PR adds support for setting the priority field in Opsgenie notifications. If a priority is provided in the notification, it will be included in the alert creation request to Opsgenie. Additionally, the code now checks for missing description in Opsgenie notifications and returns an error if it's missing.
=> feat(opsgenie): Add support for setting priority in Opsgenie notification

docs/services/opsgenie.md, pkg/services/opsgenie.go, pkg/services/opsgenie_test.go
This PR adds support for setting the alias field in the Opsgenie notifications. 
We are teammates with who created this [PR](https://github.com/argoproj/notifications-engine/pull/267). We are planning to update the Opsgenie documentation after this is merged.
=> feat(opsgenie): Add support for setting alias in Opsgenie notification

docs/services/telegram.md, go.mod, go.sum, pkg/services/telegram.go, pkg/services/telegram_test.go
This also migrates the go library to the one from OvyFlash, since the current one seems to be no longer maintained:
https://github.com/go-telegram-bot-api/telegram-bot-api/issues/695
=> Add option for Telegram to use a thread id when posting notification

docs/services/github.md, pkg/services/github.go, pkg/services/github_test.go
As it is, the `revision` that triggered the deployment is used as the `ref`, however it is useful to override so we can pass a tag, a branch or a different SHA. 
Example:
=> feat(github) add support for GitHub deployment reference

docs/services/rocketchat.md
Fixed the documentation issue in Rocket.chat that was causing issues with notification setup - changed the rocketchat-email to be the user's SAMAccountName, not the user's email address.
=> fix: Correction in Rocket.chat documentation

docs/services/slack.md
This fix the outdated slack notification documents that sync with the latest slack web ui.
=> docs: Fix outdated slack notification configuration readme

docs/services/opsgenie.md, pkg/services/opsgenie.go, pkg/services/opsgenie_test.go
Added missing fields to the Opsgenie integration, enabling the proper configuration of most fields. With this PR, issue #62 can be closed, and #329 will be superseded. If the changes from #329 are preferred, I can rebase or cherry-pick them.
**Added fields:**
- **actions:** Custom actions that will be available for the alert.
- **tags:** Tags of the alert.
- **visibleTo:** Teams and users that the alert will become visible to without sending any notification.
- **details:** Map of key-value pairs to use as custom properties of the alert.
- **entity:** Entity field of the alert that is generally used to specify which domain the alert is related to.
- **user:** Display name of the request owner.
=> Add missing fields for Opsgenie integration

docs/services/slack.md, pkg/services/slack.go, pkg/services/slack_test.go
When multiple users set triggers and templates for one slack service in monorepos, etc., there was an issue where the icon and username could not be changed. Therefore, I made it possible to set a custom username and icon in the template used for Slack notifications.
If the username and icon are already set on the service side and the username and icon are also set on the template, the template will take priority.
And there were no tests for Slack notifications, so I added them.
=> feat(slack): Support set username and icon from template in slack

pkg/controller/controller.go
Closes https://github.com/argoproj/argo-cd/issues/16891
=> feat: update log message from debug to error if processResourceWithAPI fails to run a trigger

docs/services/github.md, pkg/services/github.go, pkg/services/github_test.go
Support for GitHub Check has been added.
Feature Request Issue Link: [#19256](https://github.com/argoproj/argo-cd/issues/19256)
=> feat: Add GitHub Check Run Support

pkg/services/webhook.go
After using the webhook service in our setup, we noticed a consistent increase in the memory usage of argocd-notification-controller. Upon closer inspection, I found that the response body is not being closed after the server returns, preventing the client from returning the connection back to the pool.
The current implementation keeps creating new connections never releasing nor closing them.
=> fix: Fix memory leak in the webhook service

pkg/util/slack/client.go, pkg/util/slack/client_test.go
This wraps all interactions with the state's ThreadTSs and ChannelIDs maps in a sync.Mutex to avoid issues when recording the results of SendMessage into those maps.
=> fix(slack): [#362] avoid concurrent map writes
